### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by dismantl** [AlessandroZanatta/ML-Captcha-Solver#1]
This looks like a very interesting project and as a security researcher I'd love to try it out. I notice the code relies on a web service at `http://reversecaptcha.hax.w3challs.com` but for me that link returns a 403 Forbidden error. Is that a private service, and if so is there a way for me to run the service myself?

**Comment by AlessandroZanatta** [comment]
Hi,

This is no more than a small project done to solve a CTF-style challenge on w3challs.com (thought I stripped every reference to it, but whatever).
I suppose that you need to login on there first to see the related challenges.

**Comment by MikeyD-rbg** [comment]
@AlessandroZanatta Is it possible to train offline using .jpgs?

**Comment by MikeyD-rbg** [comment]
Or use a different url to get and solve the captchas?

**Comment by MikeyD-rbg** [comment]
@AlessandroZanatta I get this error when trying to run it;

Traceback (most recent call last):
  File "C:\Users\micha\Documents\PythonProgramming\IG\Simple-Captcha-Solver-master\src\solver.py", line 14, in <module>
    from ocr import predict
  File "C:\Users\micha\Documents\PythonProgramming\IG\Simple-Captcha-Solver-master\src\ocr\predict.py", line 6, in <module>
    model = load_model("ocr/model.model", compile=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\micha\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\saving\saving_api.py", line 199, in load_model
    raise ValueError(
ValueError: File format not supported: filepath=ocr/model.model. Keras 3 only supports V3 `.keras` files and legacy H5 format files (`.h5` extension). Note that the legacy SavedModel format is not supported by `load_model()` in Keras 3. In order to reload a TensorFlow SavedModel as an inference-only layer in Keras 3, use `keras.layers.TFSMLayer(ocr/model.model, call_endpoint='serving_default')` (note that your `call_endpoint` might have a different name).

**Comment by AlessandroZanatta** [comment]
@MikeyD-rbg Please read my previous response.

Regarding the error, I'm currently away, but it looks to be related to a version mismatch at first glance.
